[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Schedule the news scraper to run daily at 8 AM PST
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[scheduled-functions]
  "daily-news-scraper" = "0 8 * * *"
